
package com.aaaaa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Tue Jan 16 00:47:28 CST 2024
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "convertToUpperCaseResponse", namespace = "http://www.com.aaaaa")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "convertToUpperCaseResponse", namespace = "http://www.com.aaaaa")

public class ConvertToUpperCaseResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

