
package com.aaaaa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Tue Jan 16 00:47:28 CST 2024
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "convertToUpperCase", namespace = "http://www.com.aaaaa")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "convertToUpperCase", namespace = "http://www.com.aaaaa")

public class ConvertToUpperCase {

    @XmlElement(name = "inputString")
    private java.lang.String inputString;

    public java.lang.String getInputString() {
        return this.inputString;
    }

    public void setInputString(java.lang.String newInputString)  {
        this.inputString = newInputString;
    }

}

